export default [
{question:'CM of Tamilnadu ',
options:['A','B','C','D'],
answer:0,
},
{question:'2nd ',
options:['A','B','C','D'],
answer:0,
},
{question:'3rd ',
options:['A','B','C','D'],
answer:4,
},
{question:'4th ',
options:['A','B','C','D'],
answer:2,
},
 {question:'5th ',
 options:['A','B','C','D'],
 answer:1,
 },
 ]